var Calc_template = ''
    +'<div id="calc_area">'
        +'<div id="calc_display"></div>'
        +'<div class="calc_backspace calc_button" data-action="deleteLastChar">&#8592;</div>'
        +'<div class="calc_deleteChars calc_button" data-action="deleteChars">Del</div>'
        +'<div class="calc_changeSign calc_button" data-action="changeSign">&#177;</div>'
        +'<div class="calc_bracketOpen calc_button" data-type="bracketOpen">(</div>'
        +'<div class="calc_bracketClose calc_button" data-type="bracketClose">)</div>'
        +'<div class="calc_divide calc_button" data-type="operator">/</div>'
        +'<div class="calc_multiply calc_button" data-type="operator">*</div>'
        +'<div class="calc_subtract calc_button" data-type="operator">-</div>'
        +'<div class="calc_add calc_button" data-type="operator">+</div>'
        +'<div class="calc_calculate calc_button" data-action="calculate">=</div>'
        +'<div class="calc_comma calc_button" data-type="comma">.</div>'
        +'<div class="calc_null  calc_button" data-type="number">0</div>'
        +'<div class="calc_one calc_button" data-type="number">1</div>'
        +'<div class="calc_two calc_button" data-type="number">2</div>'
        +'<div class="calc_three calc_button" data-type="number">3</div>'
        +'<div class="calc_four calc_button" data-type="number">4</div>'
        +'<div class="calc_five calc_button" data-type="number">5</div>'
        +'<div class="calc_six calc_button" data-type="number">6</div>'
        +'<div class="calc_seven calc_button" data-type="number">7</div>'
        +'<div class="calc_eight calc_button" data-type="number">8</div>'
        +'<div class="calc_nine calc_button" data-type="number">9</div>'
    +'</div>';